package org.openntf.domino.i18n.impl;

import java.io.Serializable;
import java.util.Locale;

import org.openntf.domino.commons.i18n.MessageProviderAbstract;

/**
 * Example how a Messages.java, generated by Eclipse "Externalize Strings", should be modified in order to use the domino-i18n-package.
 * 
 * @author Roland Praml, FOCONIS AG
 * 
 */
public class Messages implements Serializable {

	private static final long serialVersionUID = 1L;
	private static final String BUNDLE_NAME = "de.foconis.lib.app.messages"; //$NON-NLS-1$

	public static String getString(final String key, final Object... args) {
		return MessageProviderAbstract.sGetString(BUNDLE_NAME, key, args);
	}

	public static String getInternalString(final String key, final Object... args) {
		return MessageProviderAbstract.sGetInternalString(BUNDLE_NAME, key, args);
	}

	public static String getRawString(final String key, final Locale loc) {
		return MessageProviderAbstract.sGetRawText(BUNDLE_NAME, key, loc);
	}

}
